# Standards: 0.11
---

# 1.1.19 - Disable Automounting

- name: 1.1.19 - Disable autofs
  systemd:
    name: "autofs"
    enabled: no
    state: stopped
  ignore_errors: True
  tags:
    - level-1
    - "1.1.19"
    - scored